### ISSUE TITLE
Optimization code for timesteps and noise

### ISSUE THREAD

**Issue by CyberDragon93** [SherryXTChen/TiNO-Edit#1]
Hello, thank you for your excellent work! One key contribution of your paper is the optimization of $\{t_K\}$  and noise, but I couldn't find the code for that part in the open-source release. I'm curious how you handle out-of-memory issues during the iterative optimization of $\{t_K\}$, considering it requires multiple forward passes through the diffusion U-Net.

**Comment by SherryXTChen** [comment]
Thank you for your interest in our work. OOM issue is likely to occur with 1. optimizing in image space directly, 2. large number of inference steps. This is why we develop LatentCLIP and LatentVGG so they can be used as the optimizing objects in Stable Diffusion latent space, instead of first decoding latent images to pixel space and then optimizing with respect to traditional CLIP/VGG loss, which would be very computationally expensive. 

We also use a relative small number of inference step : 10.  Although it is half of the traditionally used timestep count 20, because our starting timestep becomes smaller during optimization, thus the image is not fully noisified, a lot of the visual information can be leverage from it and a smaller inference step number works.

**Comment by CyberDragon93** [comment]
Thank you for your answer!
